package com.plataforma.gtv.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AlunoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlunoAllPropertiesEquals(Aluno expected, Aluno actual) {
        assertAlunoAutoGeneratedPropertiesEquals(expected, actual);
        assertAlunoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlunoAllUpdatablePropertiesEquals(Aluno expected, Aluno actual) {
        assertAlunoUpdatableFieldsEquals(expected, actual);
        assertAlunoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlunoAutoGeneratedPropertiesEquals(Aluno expected, Aluno actual) {
        assertThat(expected)
            .as("Verify Aluno auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlunoUpdatableFieldsEquals(Aluno expected, Aluno actual) {
        assertThat(expected)
            .as("Verify Aluno relevant properties")
            .satisfies(e -> assertThat(e.getNome()).as("check nome").isEqualTo(actual.getNome()))
            .satisfies(e -> assertThat(e.getSobrenome()).as("check sobrenome").isEqualTo(actual.getSobrenome()))
            .satisfies(e -> assertThat(e.getEmail()).as("check email").isEqualTo(actual.getEmail()))
            .satisfies(e -> assertThat(e.getNumeroTelefone()).as("check numeroTelefone").isEqualTo(actual.getNumeroTelefone()))
            .satisfies(e -> assertThat(e.getMatriculaData()).as("check matriculaData").isEqualTo(actual.getMatriculaData()))
            .satisfies(e -> assertThat(e.getMaticula()).as("check maticula").isEqualTo(actual.getMaticula()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlunoUpdatableRelationshipsEquals(Aluno expected, Aluno actual) {
        assertThat(expected)
            .as("Verify Aluno relationships")
            .satisfies(e -> assertThat(e.getEndereco()).as("check endereco").isEqualTo(actual.getEndereco()))
            .satisfies(e -> assertThat(e.getCursos()).as("check cursos").isEqualTo(actual.getCursos()));
    }
}
