package com.plataforma.gtv.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AulaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAulaAllPropertiesEquals(Aula expected, Aula actual) {
        assertAulaAutoGeneratedPropertiesEquals(expected, actual);
        assertAulaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAulaAllUpdatablePropertiesEquals(Aula expected, Aula actual) {
        assertAulaUpdatableFieldsEquals(expected, actual);
        assertAulaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAulaAutoGeneratedPropertiesEquals(Aula expected, Aula actual) {
        assertThat(expected)
            .as("Verify Aula auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAulaUpdatableFieldsEquals(Aula expected, Aula actual) {
        assertThat(expected)
            .as("Verify Aula relevant properties")
            .satisfies(e -> assertThat(e.getTituloAula()).as("check tituloAula").isEqualTo(actual.getTituloAula()))
            .satisfies(e -> assertThat(e.getDescricao()).as("check descricao").isEqualTo(actual.getDescricao()))
            .satisfies(e -> assertThat(e.getLinkVideo()).as("check linkVideo").isEqualTo(actual.getLinkVideo()))
            .satisfies(e -> assertThat(e.getLinkArquivos()).as("check linkArquivos").isEqualTo(actual.getLinkArquivos()))
            .satisfies(e -> assertThat(e.getResumo()).as("check resumo").isEqualTo(actual.getResumo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAulaUpdatableRelationshipsEquals(Aula expected, Aula actual) {
        assertThat(expected)
            .as("Verify Aula relationships")
            .satisfies(e -> assertThat(e.getMaterias()).as("check materias").isEqualTo(actual.getMaterias()));
    }
}
